services:
  - type: web
    name: crm-v3-api
    env: python
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: NEW_FIREBASE_PROJECT_ID
        sync: false
      - key: NEW_FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: NEW_FIREBASE_PRIVATE_KEY
        sync: false
      - key: NEW_FIREBASE_CLIENT_EMAIL
        sync: false
      - key: NEW_FIREBASE_CLIENT_ID
        sync: false
      - key: GSPREAD_PROJECT_ID
        sync: false
      - key: GSPREAD_PRIVATE_KEY_ID
        sync: false
      - key: GSPREAD_PRIVATE_KEY
        sync: false
      - key: GSPREAD_CLIENT_EMAIL
        sync: false
      - key: GSPREAD_CLIENT_ID
        sync: false
    healthCheckPath: /health
