services:
  - type: web
    name: crm-v3
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_BIN
        value: python3
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: NEW_FIREBASE_PROJECT_ID
        sync: false
      - key: NEW_FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: NEW_FIREBASE_PRIVATE_KEY
        sync: false
      - key: NEW_FIREBASE_CLIENT_EMAIL
        sync: false
      - key: NEW_FIREBASE_CLIENT_ID
        sync: false
      - key: GSPREAD_PROJECT_ID
        sync: false
      - key: GSPREAD_PRIVATE_KEY_ID
        sync: false
      - key: GSPREAD_PRIVATE_KEY
        sync: false
      - key: GSPREAD_CLIENT_EMAIL
        sync: false
      - key: GSPREAD_CLIENT_ID
        sync: false
    healthCheckPath: /
